# Generated by Django 4.2 on 2025-10-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('document_type', models.CharField(blank=True, choices=[('RG', 'RG'), ('CPF', 'CPF')], max_length=3, null=True, verbose_name='Tipo de Documento')),
                ('social_network', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rede Social')),
                ('social_network_type', models.CharField(blank=True, choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('OTHER', 'Outro')], max_length=12, null=True, verbose_name='Tipo de Rede Social')),
                ('profile_picture_path', models.ImageField(blank=True, null=True, upload_to='users/images/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
