# Generated by Django 4.1.7 on 2023-08-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_delete_personaldata'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='bond_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='rg',
            field=models.CharField(max_length=10, null=True, verbose_name='RG'),
        ),
    ]
