# Generated by Django 4.1.7 on 2023-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_personaldata_bond_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/%Y/%m/%d'),
        ),
    ]
