# Generated by Django 4.1.7 on 2023-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_routepath_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepath',
            name='concentration',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Horário de concentração'),
        ),
    ]
