# Generated by Django 4.1.7 on 2023-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_routepath_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepath',
            name='concentration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de concentração'),
        ),
    ]
