# Generated by Django 4.1.7 on 2023-08-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0016_alter_bond_name_alter_enrollment_bond_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('social_network', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
