# Generated by Django 4.1.7 on 2023-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Localidade'),
        ),
    ]
