# Generated by Django 4.1.7 on 2023-08-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=20, verbose_name='Situação'),
        ),
    ]
