# Generated by Django 4.1.7 on 2023-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_remove_event_banner_picture_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom',
            field=models.IntegerField(default=13, verbose_name='Zoom'),
        ),
    ]
