# Generated by Django 4.1.7 on 2023-09-19 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0030_remove_event_banner_picture_event_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.CharField(max_length=30, verbose_name='Email para contato')),
                ('social_network', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('how_knew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.howknew', verbose_name='Como soube do evento?')),
                ('route_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.routepath', verbose_name='Nome do Trajeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='enrollment_fields',
            field=models.ManyToManyField(blank=True, null=True, to='event.enrollmentfields', verbose_name='Campos do Formulário'),
        ),
    ]
