# Generated by Django 4.1.7 on 2023-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_remove_enrollmentfields_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='how_knew',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='route_path',
        ),
        migrations.RemoveField(
            model_name='enrollmentfields',
            name='social_network',
        ),
        migrations.AddField(
            model_name='enrollmentfields',
            name='name',
            field=models.CharField(default=1, max_length=25, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollmentfields',
            name='type',
            field=models.CharField(max_length=25, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='howknew',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Como soube ?'),
        ),
    ]
