# Generated by Django 4.1.7 on 2023-09-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_remove_enrollmentfields_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollmentFields',
            new_name='EnrollmentField',
        ),
    ]
