# Generated by Django 4.1.7 on 2023-09-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_remove_event_enrollment_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
    ]
