# Generated by Django 4.1.7 on 2023-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_type',
            field=models.CharField(choices=[('Type-1', 'Type-1'), ('Type-2', 'Type-2')], default='Type-1', max_length=30, verbose_name='Tipo de formulário'),
        ),
    ]
