# Generated by Django 4.1.7 on 2023-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_event_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='events/pdfs/%Y/%m/%d', verbose_name='Termo de inscrição'),
        ),
    ]
