# Generated by Django 4.1.7 on 2023-09-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_event_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.CharField(max_length=30, verbose_name='Email para contato')),
                ('term_file', models.FileField(blank=True, null=True, upload_to='events/pdfs/%Y/%m/%d', verbose_name='Termo de inscrição')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Evento')),
            ],
        ),
    ]
