# Generated by Django 4.1.7 on 2023-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_enrollmenttype2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenttype2',
            name='term_file',
            field=models.FileField(upload_to='events/enrollments/%Y/%m/%d', verbose_name='Termo de inscrição'),
        ),
    ]
