# Generated by Django 4.1.7 on 2023-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_alter_enrollmenttype2_term_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.CharField(max_length=70, verbose_name='Email para contato'),
        ),
        migrations.AlterField(
            model_name='enrollmenttype2',
            name='email',
            field=models.CharField(max_length=70, verbose_name='Email para contato'),
        ),
    ]
