# Generated by Django 4.1.7 on 2023-10-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_merge_20230929_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='secondary_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data secundária do evento'),
        ),
    ]
