# Generated by Django 4.1.7 on 2023-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_event_secondary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descrição do evento'),
        ),
    ]
