# Generated by Django 4.1.7 on 2023-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_alter_routepath_departure_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraRouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('field_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo 1')),
                ('field_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo 2')),
                ('field_three', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo 3')),
            ],
        ),
    ]
