# Generated by Django 4.1.7 on 2023-11-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_enrollmenttype2_user'),
        ('event', '0048_extrarouteinfo_event'),
    ]

    operations = [
    ]
