# Generated by Django 4.2 on 2025-10-13 14:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorpointCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon_name', models.CharField(help_text='Nome do arquivo sem extensão (ex: "restaurant", "museum")', max_length=100, unique=True, verbose_name='Nome do Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ponto',
                'verbose_name_plural': 'Categorias de Pontos',
                'db_table': 'anchorpoint_category',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_strava_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Strava da rota')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('polyline', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Marcação')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Cor da rota')),
                ('distance', models.CharField(blank=True, max_length=500, null=True, verbose_name='Distância')),
                ('active', models.BooleanField(default=False, verbose_name='Ativa')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Anchorpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('business_hours', models.CharField(blank=True, max_length=120, null=True, verbose_name='Horário de funcionamento')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('image', models.ImageField(upload_to='cities/anchor_points/photos/%Y/%m/%d', verbose_name='Imagem do ponto de apoio')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('is_event_anchorpoint', models.BooleanField(default=False, verbose_name='É um ponto de apoio de evento?')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('anchorpoint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anchorpointcategory', verbose_name='Tipo do ponto de apoio')),
            ],
            options={
                'db_table': 'anchorpoint',
            },
        ),
    ]
