# Generated by Django 4.2 on 2025-10-17 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_remove_city_anchorpoint'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorpoint',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchorpoints', to='cities.city', verbose_name='Cidade'),
        ),
    ]
