# Generated by Django 4.2 on 2025-10-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anchorpoint_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_event_route',
            field=models.BooleanField(default=False, verbose_name='É uma rota de evento?'),
        ),
    ]
