# Generated by Django 4.2 on 2025-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_route_is_event_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='external_strava_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Strava da rota'),
        ),
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Marcação no mapa'),
        ),
    ]
