# Generated by Django 4.2 on 2025-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_route_external_strava_id_alter_route_polyline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Distância'),
        ),
        migrations.AlterField(
            model_name='route',
            name='external_strava_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Strava'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_event_route',
            field=models.BooleanField(default=False, verbose_name='Rota de evento'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Polyline'),
        ),
    ]
