# Generated by Django 4.2 on 2025-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_route_options_alter_route_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Distância(Km)'),
        ),
    ]
