# Generated by Django 4.2 on 2025-12-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_route_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anchorpoint',
            options={'verbose_name': 'Ponto de Apoio', 'verbose_name_plural': 'Pontos de Apoio'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name'], 'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
    ]
