# Generated by Django 4.1.7 on 2023-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('id_route', models.CharField(max_length=50, unique=True)),
                ('polilyne', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
