# Generated by Django 4.1.7 on 2023-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('banner_photo', models.ImageField(upload_to='banner_img/%Y/%m/%d', verbose_name='Imagem do Banner')),
                ('visible', models.BooleanField(default=False, verbose_name='Visível')),
            ],
        ),
    ]
