# Generated by Django 4.1.7 on 2023-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='routes',
            field=models.ManyToManyField(to='cities.route'),
        ),
    ]
