# Generated by Django 4.1.7 on 2023-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_map',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id do Mapa'),
        ),
    ]
