# Generated by Django 4.1.7 on 2023-04-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_lat_city_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='polilyne',
            new_name='polyline',
        ),
    ]
