# Generated by Django 4.2 on 2023-04-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_alter_anchorpoint_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
