# Generated by Django 4.2 on 2023-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0021_remove_category_photo_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='cities/categories/photos/%Y/%m/%d'),
        ),
    ]
