# Generated by Django 4.2 on 2023-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='banner_photo',
            new_name='banner_image',
        ),
    ]
