# Generated by Django 4.1.7 on 2023-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_route_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='bottom_text',
            field=models.CharField(default=1, max_length=300, verbose_name='bottom_text'),
            preserve_default=False,
        ),
    ]
