# Generated by Django 4.1.7 on 2023-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0031_alter_city_bottom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimage',
            name='tittle',
            field=models.CharField(default='Lorem Ipsum', max_length=50),
            preserve_default=False,
        ),
    ]
