# Generated by Django 4.1.7 on 2023-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0036_alter_cityimage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='subtitle',
            field=models.CharField(max_length=400),
        ),
    ]
