# Generated by Django 4.1.7 on 2023-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0037_alter_cityimage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.IntegerField(default=13, verbose_name='Zoom'),
        ),
    ]
