# Generated by Django 4.1.7 on 2023-11-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0039_alter_city_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='subtitle',
            field=models.CharField(max_length=1000),
        ),
    ]
