# Generated by Django 4.1.7 on 2023-08-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0022_delete_personaldata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('bond_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Vínculo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
