# Generated by Django 4.1.7 on 2023-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_polilyne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id_route',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
