# Generated by Django 4.1.7 on 2023-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_id_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='polilyne',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
