# Generated by Django 4.1.7 on 2023-05-20 01:42

import cities.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0025_route_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('iconUrl', models.FileField(upload_to='events/icons/%Y/%m/%d', validators=[cities.validators.validate_file_extension_category])),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude do Ponto')),
                ('lng', models.CharField(max_length=20, verbose_name='Longitude do Ponto')),
                ('active', models.BooleanField(default=False, verbose_name='Estado do Ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Evento')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Descrição do evento')),
                ('lat', models.CharField(blank=True, default='-29.95', max_length=20, null=True, verbose_name='Latitute de Mapa')),
                ('lng', models.CharField(blank=True, default='-51.64', max_length=20, null=True, verbose_name='Longitude do Mapa')),
                ('points', models.ManyToManyField(blank=True, null=True, to='event.anchorpoint', verbose_name='Pontos do Evento')),
            ],
        ),
        migrations.CreateModel(
            name='HowKnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Como soube ?')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do caminho')),
                ('time', models.CharField(max_length=10, verbose_name='Horário de Sáida')),
                ('departure_location', models.CharField(max_length=50, verbose_name='Local de Partida')),
                ('active', models.BooleanField(default=False, verbose_name='Estado da Rota')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.route')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/images/%Y/%m/%d')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='routes_data',
            field=models.ManyToManyField(blank=True, null=True, to='event.routepath', verbose_name='Rotas do Evento'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.CharField(max_length=30, verbose_name='Email para contato')),
                ('social_network', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('bond_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Categoria')),
                ('how_knew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.howknew', verbose_name='Como soube do evento?')),
                ('route_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.routepath', verbose_name='Nome do Trajeto')),
            ],
        ),
    ]
