# Generated by Django 4.2 on 2025-10-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Descrição do evento')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data do evento')),
                ('secondary_date', models.DateField(blank=True, null=True, verbose_name='Data secundária do evento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitute')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade')),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=20, verbose_name='Situação')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/images/%Y/%m/%d', verbose_name='Banner do evento')),
                ('zoom', models.IntegerField(default=13, verbose_name='Zoom')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='events/pdfs/%Y/%m/%d', verbose_name='Termo de inscrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('anchorpoint', models.ManyToManyField(blank=True, to='core.anchorpoint', verbose_name='Pontos do Evento')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vínculo')),
            ],
            options={
                'db_table': 'event_bond',
            },
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_form',
            },
        ),
        migrations.CreateModel(
            name='EventFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('validation', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='event.eventform')),
            ],
            options={
                'db_table': 'event_form_field',
            },
        ),
        migrations.CreateModel(
            name='EventHowknew',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Como soube ?')),
            ],
            options={
                'db_table': 'event_howknew',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(max_length=500, verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'db_table': 'warning',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='events/images/%Y/%m/%d')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event')),
            ],
            options={
                'db_table': 'event_image',
            },
        ),
        migrations.CreateModel(
            name='EventFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='event.enrollment')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventformfield')),
            ],
            options={
                'db_table': 'event_form_response',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_forms', to='event.eventform', verbose_name='Formulário de inscrição'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='warning',
            field=models.ManyToManyField(blank=True, to='event.warning', verbose_name='Avisos'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do caminho')),
                ('time', models.CharField(max_length=100, verbose_name='Horário de Saída')),
                ('departure_location', models.CharField(max_length=255, verbose_name='Local de Partida')),
                ('concentration', models.CharField(default='----', max_length=255, verbose_name='Horário de concentração')),
                ('active', models.BooleanField(default=False, verbose_name='Estado da Rota')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_routes', to='event.event')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'db_table': 'event_route',
                'unique_together': {('event', 'route')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('event', 'user')},
        ),
    ]
