# Generated by Django 4.2 on 2023-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_rename_banner_photo_city_banner_image'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, to='cities.route', verbose_name='Rotas do Evento'),
        ),
    ]
