# Generated by Django 4.2 on 2025-10-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='warning',
        ),
        migrations.AddField(
            model_name='eventbond',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de nome'),
        ),
        migrations.AddField(
            model_name='eventhowknew',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de nome'),
        ),
        migrations.AddField(
            model_name='warning',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_warning', to='event.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventhowknew',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='warning',
            table='event_warning',
        ),
    ]
