# Generated by Django 4.2 on 2025-10-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_warning_eventbond_code_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_path',
            new_name='image',
        ),
    ]
