# Generated by Django 4.1.7 on 2023-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_routepath_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepath',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do caminho'),
        ),
    ]
