# Generated by Django 4.2 on 2025-10-28 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_image_path_eventimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventroute'),
        ),
        migrations.AlterField(
            model_name='eventroute',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='event.event'),
        ),
    ]
