# Generated by Django 4.2 on 2023-05-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
