# Generated by Django 4.2 on 2025-12-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_enrollment_route_alter_eventroute_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventbond',
            options={'verbose_name': 'Vínculo', 'verbose_name_plural': 'Vínculos'},
        ),
        migrations.AlterModelOptions(
            name='eventform',
            options={'verbose_name': 'Formulário de Evento', 'verbose_name_plural': 'Formulários de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventformfield',
            options={'verbose_name': 'Campo de Formulário', 'verbose_name_plural': 'Campos de Formulários'},
        ),
        migrations.AlterModelOptions(
            name='eventformresponse',
            options={'verbose_name': 'Resposta de Formulário', 'verbose_name_plural': 'Respostas de Formulários'},
        ),
        migrations.AlterModelOptions(
            name='eventhowknew',
            options={'verbose_name': 'Como Ficou Sabendo', 'verbose_name_plural': 'Como Ficou Sabendo'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Imagem de Evento', 'verbose_name_plural': 'Imagens de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventroute',
            options={'verbose_name': 'Rota de Evento', 'verbose_name_plural': 'Rotas de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='warning',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
