# Generated by Django 4.2 on 2023-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Descrição do evento'),
        ),
    ]
