# Generated by Django 4.1.7 on 2023-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_routepath_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepath',
            name='concentration',
            field=models.CharField(default='Não necessário', max_length=100, verbose_name='Horário de concentração'),
        ),
        migrations.AlterField(
            model_name='routepath',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Horário de Sáida'),
        ),
    ]
