# Generated by Django 4.1.7 on 2023-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_routepath_concentration_alter_routepath_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepath',
            name='concentration',
            field=models.CharField(default='----', max_length=100, verbose_name='Horário de concentração'),
        ),
    ]
