# Generated by Django 4.1.7 on 2023-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='warnings',
            field=models.ManyToManyField(blank=True, null=True, to='event.warning', verbose_name='Avisos'),
        ),
    ]
