# Generated by Django 4.1.7 on 2023-05-27 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_warning_event_event_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de criação'),
        ),
    ]
