# Generated by Django 4.1.7 on 2023-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_lat_event_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('class_field', models.CharField(max_length=255)),
                ('how_knew', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
