# Generated by Django 4.1.7 on 2023-05-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='class_field',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='how_knew',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='rg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='route',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='bond_choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.bond'),
            preserve_default=False,
        ),
    ]
