# Generated by Django 4.1.7 on 2023-05-15 00:55

import cities.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_route_color'),
        ('event', '0012_bond_remove_enrollment_class_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do ponto')),
                ('iconUrl', models.FileField(upload_to='events/icons/%Y/%m/%d', validators=[cities.validators.validate_file_extension_category])),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude do Ponto')),
                ('lng', models.CharField(max_length=20, verbose_name='Longitude do Ponto')),
                ('active', models.BooleanField(default=False, verbose_name='Estado do Ponto')),
            ],
        ),
        migrations.CreateModel(
            name='HowKnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Como soube ?')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='route',
        ),
        migrations.RemoveField(
            model_name='event',
            name='routes',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.CharField(default=None, max_length=30, verbose_name='Email para contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='social_network',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Nome do Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='bond_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='rg',
            field=models.CharField(max_length=10, verbose_name='RG'),
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do caminho')),
                ('time', models.CharField(max_length=10, verbose_name='Horário de Sáida')),
                ('departure_location', models.CharField(max_length=50, verbose_name='Local de Partida')),
                ('active', models.BooleanField(default=False, verbose_name='Estado da Rota')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.route')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='route_path',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event.routepath', verbose_name='Nome do Trajeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, to='event.anchorpoint', verbose_name='Pontos do Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='routes_data',
            field=models.ManyToManyField(blank=True, null=True, to='event.routepath', verbose_name='Rotas do Evento'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='how_knew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.howknew', verbose_name='Como soube do evento?'),
        ),
    ]
