# Generated by Django 4.1.7 on 2023-06-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_enrollment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
    ]
