# Generated by Django 4.1.7 on 2023-06-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_enrollment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='bond_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Vínculo'),
        ),
    ]
