# Generated by Django 4.1.7 on 2023-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_bond_name_alter_enrollment_bond_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom',
            field=models.IntegerField(default=13),
        ),
    ]
