# Generated by Django 4.1.7 on 2023-08-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_personaldata_bond_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='full_name',
        ),
    ]
