# Generated by Django 4.1.7 on 2023-09-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_zoom'),
        ('event', '0027_enrollment_user'),
    ]

    operations = [
    ]
