# Generated by Django 4.1.7 on 2023-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom',
            field=models.IntegerField(default=13, verbose_name='Zoom'),
        ),
    ]
