# Generated by Django 4.1.7 on 2023-09-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_zoom'),
        ('event', '0028_event_zoom'),
    ]

    operations = [
    ]
