# Generated by Django 4.1.7 on 2023-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_merge_0017_event_zoom_0028_event_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zoom',
            field=models.IntegerField(default=13, verbose_name='Zoom'),
        ),
    ]
