# Generated by Django 4.1.7 on 2023-09-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_event_banner_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_picture',
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/%Y/%m/%d', verbose_name='Banner do evento'),
        ),
    ]
