# Generated by Django 4.1.7 on 2023-09-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_event_zoom'),
        ('event', '0042_alter_enrollment_email_alter_enrollmenttype2_email'),
    ]

    operations = [
    ]
