# Generated by Django 4.1.7 on 2024-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_enrollment3passeiociclistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form_type',
            field=models.CharField(choices=[('Type-1', 'Type-1'), ('Type-2', 'Type-2'), ('Type-3', 'Type-3')], default='Type-1', max_length=30, verbose_name='Tipo de formulário'),
        ),
    ]
