# Generated by Django 4.1.7 on 2024-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_alter_event_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment3passeiociclistico',
            name='rg',
            field=models.CharField(max_length=11, verbose_name='RG'),
        ),
    ]
