# Generated by Django 4.1.7 on 2025-03-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0052_alter_enrollment3passeiociclistico_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment4PasseioCiclistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.CharField(max_length=70, verbose_name='Email para contato')),
                ('social_network', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('bond_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Vínculo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Evento')),
                ('how_knew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.howknew', verbose_name='Como soube do evento?')),
                ('route_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.routepath', verbose_name='Nome do Trajeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
