# Generated by Django 4.1.7 on 2025-03-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0053_enrollment4passeiociclistico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment4PasseioCiclistico',
        ),
    ]
