# Generated by Django 4.2 on 2025-11-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urls',
            new_name='URL',
        ),
    ]
