# Generated by Django 4.2 on 2025-11-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_rename_urls_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='collaborators_id',
            new_name='collaborator',
        ),
    ]
