# Generated by Django 4.2 on 2025-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0003_rename_collaborators_id_url_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='picture',
            field=models.CharField(max_length=255),
        ),
    ]
