# Generated by Django 4.2 on 2025-11-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0004_alter_collaborators_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
