# Generated by Django 4.2 on 2025-11-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0005_collabs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collabs',
        ),
    ]
