# Generated by Django 4.2 on 2025-12-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0006_delete_collabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='picture',
            field=models.BinaryField(),
        ),
    ]
