# Generated by Django 4.2 on 2025-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0007_alter_collaborators_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='picture',
            field=models.ImageField(upload_to='Collaborators/'),
        ),
    ]
