# Generated by Django 4.2 on 2025-12-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0008_alter_collaborators_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborators',
            options={'ordering': ['-is_current', 'name']},
        ),
        migrations.AddField(
            model_name='collaborators',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Membro atual do projeto'),
        ),
    ]
