# Generated by Django 4.2 on 2025-12-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0009_alter_collaborators_options_collaborators_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborators',
            options={'ordering': ['-is_current', 'name'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
