# Generated by Django 4.2 on 2025-12-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0010_alter_collaborators_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Collaborators/'),
        ),
    ]
