# Generated by Django 4.2 on 2025-10-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('banner_image', models.ImageField(upload_to='cities/images/banner_photos/%Y/%m/%d', verbose_name='Imagem do Banner')),
                ('latitude', models.DecimalField(decimal_places=6, default='-29.958491', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, default='-51.629398', max_digits=9, verbose_name='Longitude')),
                ('active', models.BooleanField(default=False, verbose_name='Acessível')),
                ('visible', models.BooleanField(default=False, verbose_name='Visível')),
                ('zoom', models.IntegerField(default=14, verbose_name='Zoom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('anchorpoint', models.ManyToManyField(blank=True, to='core.anchorpoint', verbose_name='Pontos de apoio')),
                ('route', models.ManyToManyField(blank=True, to='core.route', verbose_name='Rotas')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='cities/images/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cities.city')),
            ],
            options={
                'db_table': 'city_image',
            },
        ),
    ]
