# Generated by Django 4.1.7 on 2024-09-20 06:30

import cities.validators
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100, verbose_name='Nome da rua')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número do comércio')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='AnchorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(upload_to='cities/anchor_points/photos/%Y/%m/%d', verbose_name='Imagem do ponto de apoio')),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude')),
                ('lng', models.CharField(max_length=20, verbose_name='Longitude')),
                ('business_hours', models.CharField(max_length=120, verbose_name='Horário de funcionamento')),
                ('phone', models.CharField(default='(51) ', max_length=20, verbose_name='Telefone')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.address', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('image', models.FileField(upload_to='cities/categories/photos/%Y/%m/%d', validators=[cities.validators.validate_file_extension_category])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('lat', models.CharField(default='-29.95', max_length=50, verbose_name='Latitude')),
                ('lng', models.CharField(default='-51.64', max_length=50, verbose_name='Longitude')),
                ('zoom', models.IntegerField(default=14, verbose_name='Zoom')),
                ('banner_image', models.ImageField(upload_to='cities/images/banner_photos/%Y/%m/%d', verbose_name='Imagem do Banner')),
                ('visible', models.BooleanField(default=False, verbose_name='Visível')),
                ('active', models.BooleanField(default=False, verbose_name='Acessível')),
                ('points', models.ManyToManyField(blank=True, null=True, to='cities.anchorpoint', verbose_name='Pontos de apoio')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Cor da rota')),
                ('id_route', models.CharField(max_length=50, unique=True, verbose_name='Id da rota')),
                ('polyline', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Marcação')),
                ('distance', models.CharField(blank=True, max_length=500, null=True, verbose_name='Distância')),
                ('active', models.BooleanField(default=False, verbose_name='Ativa')),
            ],
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities/images/%Y/%m/%d')),
                ('tittle', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cities.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, to='cities.route', verbose_name='Rotas'),
        ),
        migrations.AddField(
            model_name='anchorpoint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.category', verbose_name='Tipo do comérico'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city', verbose_name='Cidade'),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id do Segmento')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Segmento')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cities.route', verbose_name='Rota')),
            ],
            options={
                'unique_together': {('id', 'route')},
            },
        ),
    ]
