# Generated by Django 4.1.7 on 2024-09-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
