# Generated by Django 4.2 on 2025-10-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='anchorpoint',
        ),
    ]
