# Generated by Django 4.1.7 on 2024-09-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_delete_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id do Segmento')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Segmento')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cities.route', verbose_name='Rota')),
            ],
            options={
                'unique_together': {('id', 'route')},
            },
        ),
    ]
