# Generated by Django 4.2 on 2025-12-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_remove_city_anchorpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
    ]
