# Generated by Django 4.1.7 on 2024-09-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_segment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set(),
        ),
    ]
