# Generated by Django 4.1.7 on 2024-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_segment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='city',
            field=models.CharField(default='Não Informada', max_length=250, verbose_name='Cidade'),
        ),
    ]
