# Generated by Django 4.1.7 on 2024-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_segment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='city',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Cidade'),
        ),
    ]
