# Generated by Django 4.1.7 on 2023-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_city_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='banner_photo',
            field=models.ImageField(upload_to='cities/images/banner_photos/%Y/%m/%d', verbose_name='Imagem do Banner'),
        ),
    ]
