# Generated by Django 4.1.7 on 2023-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(default='-29.95', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.CharField(default='-51.64', max_length=50),
        ),
    ]
