# Generated by Django 4.2 on 2023-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_rename_polilyne_route_polyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='cities/catogories/photos/%Y/%m/%d', verbose_name='Imagem da Categoria')),
            ],
        ),
    ]
