# Generated by Django 4.1.7 on 2024-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_segment_state_alter_segment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='country',
            field=models.CharField(default='Não Informado', max_length=250, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='segment',
            name='distance',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Distância'),
        ),
    ]
