# Generated by Django 4.1.7 on 2024-09-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_segment_country_segment_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='average_grade',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Inclinação Média'),
        ),
        migrations.AddField(
            model_name='segment',
            name='total_elevation_gain',
            field=models.CharField(default='Não Informado', max_length=250, null=True, verbose_name='Ganho de Elevação'),
        ),
    ]
