# Generated by Django 4.2 on 2023-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_anchorpoint_active_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorpoint',
            name='image',
            field=models.ImageField(default=None, upload_to='cities/anchor_points/photos/%Y/%m/%d', verbose_name='Imagem do ponto de apoio'),
        ),
    ]
