# Generated by Django 4.1.7 on 2024-09-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_segment_average_grade_segment_total_elevation_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='average_grade',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='total_elevation_gain',
        ),
    ]
