# Generated by Django 4.2 on 2023-04-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_anchorpoint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorpoint',
            name='image',
            field=models.ImageField(upload_to='cities/anchor_points/photos/%Y/%m/%d', verbose_name='Imagem do ponto de apoio'),
        ),
    ]
