# Generated by Django 4.1.7 on 2024-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_remove_segment_average_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='average_grade',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Inclinação Média'),
        ),
        migrations.AddField(
            model_name='segment',
            name='elevation_high',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Elevação Máxima'),
        ),
        migrations.AddField(
            model_name='segment',
            name='elevation_low',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Elevação Mínima'),
        ),
    ]
