# Generated by Django 4.1.7 on 2024-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_segment_average_grade_segment_elevation_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='athlete_count',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Contagem de Atletas'),
        ),
        migrations.AddField(
            model_name='segment',
            name='effort_count',
            field=models.CharField(default='Não Informadas', max_length=250, null=True, verbose_name='Tentativas'),
        ),
    ]
