# Generated by Django 4.1.7 on 2024-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_segment_athlete_count_segment_effort_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='effort_count',
        ),
    ]
