# Generated by Django 4.2 on 2023-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_alter_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default=None, upload_to='cities/categories/photos/%Y/%m/%d'),
        ),
    ]
