# Generated by Django 4.1.7 on 2024-09-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_remove_segment_effort_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='athlete_count',
        ),
    ]
