# Generated by Django 4.1.7 on 2024-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0021_remove_segment_athlete_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='polyline',
            field=models.CharField(default='Não Informada', max_length=5000, null=True, verbose_name='Marcação'),
        ),
    ]
