# Generated by Django 4.1.7 on 2024-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_segment_total_elevation_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='athlete_count',
            field=models.CharField(default='Não Informada', max_length=250, null=True, verbose_name='Contagem de Atletas'),
        ),
        migrations.AddField(
            model_name='segment',
            name='effort_count',
            field=models.CharField(default='Não Informadas', max_length=250, null=True, verbose_name='Tentativas'),
        ),
    ]
