# Generated by Django 4.1.7 on 2024-09-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0024_segment_athlete_count_segment_effort_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='color',
        ),
        migrations.AlterField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distância'),
        ),
        migrations.AlterField(
            model_name='route',
            name='id_route',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID da Rota'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome da Rota'),
        ),
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True, null=True, verbose_name='Polyline'),
        ),
    ]
