# Generated by Django 4.1.7 on 2023-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0030_alter_city_bottom_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='bottom_text',
            field=models.CharField(max_length=800, verbose_name='bottom_text'),
        ),
    ]
