# Generated by Django 4.1.7 on 2023-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0033_city_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Acessível'),
        ),
    ]
