# Generated by Django 4.1.7 on 2023-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0035_remove_city_bottom_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='subtitle',
            field=models.CharField(max_length=300),
        ),
    ]
