# Generated by Django 4.1.7 on 2023-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0038_city_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zoom',
            field=models.IntegerField(default=14, verbose_name='Zoom'),
        ),
    ]
