# Generated by Django 4.2 on 2025-10-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.CharField(default=-29.95, max_length=50)),
                ('lng', models.CharField(default=51.64, max_length=50)),
                ('zoom', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CityManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='AnchorPointsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.anchorpoint')),
            ],
        ),
    ]
