# Generated by Django 4.2 on 2025-11-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorpointsmanager',
            name='anchor_point',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='AnchorPointsManager',
        ),
    ]
