# Generated by Django 4.2 on 2025-12-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_anchorpointsmanager_anchor_point_delete_home_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymanager',
            options={'verbose_name': 'Gerenciador de Cidade', 'verbose_name_plural': 'Gerenciadores de Cidades'},
        ),
    ]
