# Generated by Django 4.1.7 on 2023-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id_city', models.IntegerField(primary_key=True, serialize=False)),
                ('name_city', models.CharField(max_length=100)),
            ],
        ),
    ]
