# Generated by Django 4.1.7 on 2023-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
