# Generated by Django 4.1.7 on 2023-04-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_photo_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='photo_city',
            new_name='banner_photo_city',
        ),
    ]
