# Generated by Django 4.1.7 on 2023-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_home_banner_photo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='id_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
