# Generated by Django 4.1.7 on 2023-04-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_home_id_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='banner_photo_city',
        ),
        migrations.RemoveField(
            model_name='home',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='home',
            name='name_city',
        ),
    ]
