# Generated by Django 4.1.7 on 2023-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_city_citymanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.CharField(default=-29.95, max_length=50)),
                ('lng', models.CharField(default=51.64, max_length=50)),
            ],
        ),
    ]
