# Generated by Django 4.1.7 on 2023-04-11 13:18
from django.db import migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
    ]
