# Generated by Django 4.1.7 on 2023-04-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_lat_city_lng'),
        ('home', '0014_rename_home_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityManager',
        ),
    ]
