# Generated by Django 4.2 on 2023-04-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_anchorpoint_active_alter_address_city_and_more'),
        ('home', '0016_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPointsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.anchorpoint')),
            ],
        ),
    ]
